"use client";
import React from "react";
import { useState, useEffect } from "react";
import Navbar from "../navbar";

const bots = [
  {
    name: "Popular",
    title: "AI Search Engine",
    description:
      "An advanced web search app powered by artificial intelligence, designed to give users a...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Popular",
    title: "Claude",
    description:
      "Anthropic's Claude 3.5 Sonnet is excellent for complex tasks like coding and handling long...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Popular",
    title: "DeepSeek",
    description:
      "DeepSeek V3, the latest innovation in AI technology, excels at advanced reasoning, precise data...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Programming",
    title: "Google Gemini",
    description:
      "Gemini, Google's most advanced AI, is designed for a wide range of tasks, including handling text,...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Popular",
    title: "Image Generation",
    description:
      "Bring your ideas to life—create stunning images from just a few words!",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Education",
    title: "Music Generation",
    description:
      "No better way to express your feelings than a song generated by you, based on your words! Just...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Lifestyle",
    title: "DeepSeek",
    description:
      "DeepSeek V3, the latest innovation in AI technology, excels at advanced reasoning, precise data...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Writing",
    title: "Google Gemini",
    description:
      "Gemini, Google's most advanced AI, is designed for a wide range of tasks, including handling text,...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "AI Models",
    title: "Image Generation",
    description:
      "Bring your ideas to life—create stunning images from just a few words!",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
  {
    name: "Education",
    title: "Music Generation",
    description:
      "No better way to express your feelings than a song generated by you, based on your words! Just...",
    tag: "New",
    details: "Engineered for advanced AI search",
  },
];

const Page = () => {
  const [filteredBots, setFilteredBots] = useState(bots);
  const [category, setCategory] = useState("Popular");
  const [activeButton, setActiveButton] = useState("Popular");
  useEffect(() => {
    if (typeof window !== "undefined") {
      try {
        const storedUser = localStorage.getItem("user");
        if (!storedUser) {
          router.push("/login");
          return;
        } else {
          const user = JSON.parse(storedUser);
        }
      } catch (error) {}
    }
  }, []);

  const handleButtonClick = (category) => {
    setCategory(category);
    setActiveButton(category);
    if (category === "All") {
      setFilteredBots(bots);
    } else {
      setFilteredBots(bots.filter((bot) => bot.name === category));
    }
  };

  return (
    <>
      <div className="flex w-full justify-between bg-gray-50 text-sm">
        <Navbar />
        <div className="min-h-screen bg-gray-50 flex flex-col items-center mt-4 ml-auto w-[80%]">
          <div className="grid grid-cols-1 gap-6 items-center mr-20 ml-20">
            <div className="flex border mt-14 rounded-md p-1 bg-gray-200 rounded-l-full rounded-r-full mr-20 ml-20">
              {[
                "Popular",
                "AI Models",
                "Writing",
                "Education",
                "Lifestyle",
                "Programming",
              ].map((categoryName) => (
                <button
                  key={categoryName}
                  onClick={() => handleButtonClick(categoryName)}
                  className={`items-center text-gray-600 pl-9 pr-9 p-2 rounded-l-full rounded-r-full hover:text-black
                      ${
                        activeButton === categoryName ? "bg-white border" : ""
                      }`}
                >
                  {categoryName}
                </button>
              ))}
            </div>
            <div className="min-h-screen p-6">
              <div className="justify-center text-center">
                <h1 className="text-3xl text-gray-700 mb-3 mt-8 font-bold">
                  {category}
                </h1>
              </div>
              <header className="mb-8 justify-center text-center">
                <h1 className="text-lg text-gray-400">
                  Explore the most popular bots for your everyday tasks.
                </h1>
              </header>
              <div className="grid grid-cols-1 mr-8 ml-8 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredBots.map((bot, index) => (
                  <div
                    key={bot.title + index}
                    className="p-4 bg-white shadow rounded-lg hover:bg-gray-100"
                  >
                    <div className="flex justify-between items-center">
                      <div className="w-10 h-10 p-1 mb-5 ">
                        <svg
                          viewBox="0 0 42 42"
                          fill="none"
                          className="CustomIcon-module__icon___zGR29 CustomIcon-module__icon--large___HBGvG"
                        >
                          <g clipPath="url(#clip0_11185_26182)">
                            <path
                              d="M0.5 21C0.5 9.678 9.678 0.5 21 0.5C32.322 0.5 41.5 9.678 41.5 21C41.5 32.322 32.322 41.5 21 41.5C9.678 41.5 0.5 32.322 0.5 21Z"
                              fill="white"
                            ></path>
                            <g clipPath="url(#clip1_11185_26182)">
                              <path
                                d="M31.2789 18.8229C31.8234 17.1886 31.6359 15.3984 30.7652 13.9119C29.4557 11.6319 26.8232 10.4589 24.2522 11.0109C23.1084 9.72236 21.4652 8.98961 19.7424 9.00011C17.1144 8.99411 14.7827 10.6861 13.9742 13.1866C12.2859 13.5324 10.8287 14.5891 9.97594 16.0869C8.65669 18.3609 8.95744 21.2274 10.7199 23.1774C10.1754 24.8116 10.3629 26.6019 11.2337 28.0884C12.5432 30.3684 15.1757 31.5414 17.7467 30.9894C18.8897 32.2779 20.5337 33.0106 22.2564 32.9994C24.8859 33.0061 27.2184 31.3126 28.0269 28.8099C29.7152 28.4641 31.1724 27.4074 32.0252 25.9096C33.3429 23.6356 33.0414 20.7714 31.2797 18.8214L31.2789 18.8229ZM22.2579 31.4311C21.2057 31.4326 20.1864 31.0644 19.3787 30.3901C19.4154 30.3706 19.4792 30.3354 19.5204 30.3099L24.2994 27.5499C24.5439 27.4111 24.6939 27.1509 24.6924 26.8696V20.1324L26.7122 21.2986C26.7339 21.3091 26.7482 21.3301 26.7512 21.3541V26.9334C26.7482 29.4144 24.7389 31.4259 22.2579 31.4311ZM12.5949 27.3039C12.0677 26.3934 11.8779 25.3261 12.0587 24.2904C12.0939 24.3114 12.1562 24.3496 12.2004 24.3751L16.9794 27.1351C17.2217 27.2769 17.5217 27.2769 17.7647 27.1351L23.5989 23.7661V26.0986C23.6004 26.1226 23.5892 26.1459 23.5704 26.1609L18.7397 28.9501C16.5879 30.1891 13.8399 29.4526 12.5957 27.3039H12.5949ZM11.3372 16.8721C11.8622 15.9601 12.6909 15.2626 13.6779 14.9004C13.6779 14.9416 13.6757 15.0144 13.6757 15.0654V20.5861C13.6742 20.8666 13.8242 21.1269 14.0679 21.2656L19.9022 24.6339L17.8824 25.8001C17.8622 25.8136 17.8367 25.8159 17.8142 25.8061L12.9827 23.0146C10.8354 21.7711 10.0989 19.0239 11.3364 16.8729L11.3372 16.8721ZM27.9317 20.7339L22.0974 17.3649L24.1172 16.1994C24.1374 16.1859 24.1629 16.1836 24.1854 16.1934L29.0169 18.9826C31.1679 20.2254 31.9052 22.9771 30.6624 25.1281C30.1367 26.0386 29.3087 26.7361 28.3224 27.0991V21.4134C28.3247 21.1329 28.1754 20.8734 27.9324 20.7339H27.9317ZM29.9417 17.7084C29.9064 17.6866 29.8442 17.6491 29.7999 17.6236L25.0209 14.8636C24.7787 14.7219 24.4787 14.7219 24.2357 14.8636L18.4014 18.2326V15.9001C18.3999 15.8761 18.4112 15.8529 18.4299 15.8379L23.2607 13.0509C25.4124 11.8096 28.1634 12.5484 29.4039 14.7009C29.9282 15.6099 30.1179 16.6741 29.9402 17.7084H29.9417ZM17.3034 21.8656L15.2829 20.6994C15.2612 20.6889 15.2469 20.6679 15.2439 20.6439V15.0646C15.2454 12.5806 17.2607 10.5676 19.7447 10.5691C20.7954 10.5691 21.8124 10.9381 22.6202 11.6101C22.5834 11.6296 22.5204 11.6649 22.4784 11.6904L17.6994 14.4504C17.4549 14.5891 17.3049 14.8486 17.3064 15.1299L17.3034 21.8641V21.8656ZM18.4007 19.5001L20.9994 17.9994L23.5982 19.4994V22.5001L20.9994 24.0001L18.4007 22.5001V19.5001Z"
                                fill="black"
                              ></path>
                            </g>
                            <path
                              d="M41.3443 21.0002C41.3443 9.76457 32.2359 0.65625 21.0002 0.65625C9.76457 0.65625 0.65625 9.76457 0.65625 21.0002C0.65625 32.2359 9.76457 41.3443 21.0002 41.3443C32.2359 41.3443 41.3443 32.2359 41.3443 21.0002Z"
                              stroke="#EEEEEE"
                              strokeWidth="1.313"
                            ></path>
                          </g>
                          <defs>
                            <clipPath id="clip0_11185_26182">
                              <rect width="42" height="42" fill="white"></rect>
                            </clipPath>
                            <clipPath id="clip1_11185_26182">
                              <rect
                                width="24"
                                height="24"
                                fill="white"
                                transform="translate(9 9)"
                              ></rect>
                            </clipPath>
                          </defs>
                        </svg>
                      </div>

                      <span className="text-sm bg-green-100 text-green-700 px-2 py-1 rounded">
                        {bot.tag}
                      </span>
                    </div>
                    <h2 className="text-lg font-semibold text-black">
                      {bot.title}
                    </h2>
                    <p className="mr-10 text-gray-300">{bot.details}</p>
                    <p className="mt-2 text-gray-600 mr-3">{bot.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Page;
