// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { NextAuthProvider } from "./Providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <NextAuthProvider>
//         {children}
//         </NextAuthProvider>
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./Providers";
import { ChatProvider } from "./chatContext"; 
import Header from "./header";
import { CreditProvider } from "../context/creditContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
          <>
            <Header />
            <NextAuthProvider>
              <ChatProvider>
               <CreditProvider>  {children}</CreditProvider>
                </ChatProvider>
            </NextAuthProvider>
          </>
        
      </body>
    </html>
  );
}

